/*
 * Copyright 2017-2021 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aot.std.sourcegen;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.ParameterizedTypeName;
import io.micronaut.aot.core.AOTContext;
import io.micronaut.aot.core.AOTModule;
import io.micronaut.aot.core.codegen.AbstractCodeGenerator;
import io.micronaut.context.env.ConstantPropertySources;
import io.micronaut.context.env.PropertySource;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * Generates a "constant" property source, that is to say a
 * {@link PropertySource} which properties are known at build time
 * (and constant).
 * It registers the property sources generated by {@link GenericPropertySourceGenerator},
 * and excludes the configuration files they replace.
 */
@AOTModule(
        id = ConstantPropertySourcesSourceGenerator.ID,
        description = ConstantPropertySourcesSourceGenerator.DESCRIPTION,
        dependencies = GenericPropertySourceGenerator.ID
)
public class ConstantPropertySourcesSourceGenerator extends AbstractCodeGenerator {
    public static final String ID = "sealed.property.source";
    public static final String DESCRIPTION = "Precomputes property sources at build time";

    private static final Logger LOG = LoggerFactory.getLogger(ConstantPropertySourcesSourceGenerator.class);

    @Override
    public void generate(@NonNull AOTContext context) {
        List<GeneratedPropertySources.Source> generated = context.get(GeneratedPropertySources.class)
            .map(GeneratedPropertySources::sources)
            .orElse(List.of());
        List<GeneratedPropertySources.Source> registered = withoutAmbiguousResources(generated);
        context.registerStaticOptimization("AotConstantPropertySources", ConstantPropertySources.class, initializer -> {
            initializer.addStatement("$T propertySources = new $T()",
                    ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(PropertySource.class)),
                    ParameterizedTypeName.get(ClassName.get(ArrayList.class), ClassName.get(PropertySource.class))
            );
            for (GeneratedPropertySources.Source source : registered) {
                initializer.addStatement("propertySources.add(new $T())", ClassName.get(context.getPackageName(), source.simpleClassName()));
            }
            initializer.addStatement("return new $T(propertySources)", ConstantPropertySources.class);
        });
        for (GeneratedPropertySources.Source source : registered) {
            source.files().forEach(context::registerExcludedResource);
        }
    }

    /**
     * Micronaut only uses the first constant property source with a given name, while it applies
     * the files of every loader. When two loaders produce a property source with the same name,
     * for example from application.properties and application.yml, all the files of that resource
     * are kept: registering only some of its property sources would change which values win,
     * since a kept application file would then override a generated application-dev source.
     *
     * @param generated the generated property sources
     * @return the property sources which can be registered
     */
    private static List<GeneratedPropertySources.Source> withoutAmbiguousResources(List<GeneratedPropertySources.Source> generated) {
        Set<String> names = new HashSet<>();
        Set<String> ambiguousNames = new TreeSet<>();
        Set<String> ambiguousResources = new TreeSet<>();
        for (GeneratedPropertySources.Source source : generated) {
            if (!names.add(source.name())) {
                ambiguousNames.add(source.name());
                ambiguousResources.add(source.resource());
            }
        }
        if (ambiguousResources.isEmpty()) {
            return generated;
        }
        LOG.warn("Keeping the configuration files of {}: more than one property source loader produced {}",
            ambiguousResources, ambiguousNames);
        return generated.stream()
            .filter(source -> !ambiguousResources.contains(source.resource()))
            .toList();
    }
}
