/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aot.std.sourcegen;

import io.micronaut.aot.core.AOTContext;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The property sources generated by {@link GenericPropertySourceGenerator}, stored in the
 * {@link AOTContext} so that {@link ConstantPropertySourcesSourceGenerator} can register them.
 */
final class GeneratedPropertySources {

    private final List<Source> sources = new ArrayList<>();

    private GeneratedPropertySources() {
    }

    /**
     * Returns the registry of the given context, creating it if needed.
     *
     * @param context the AOT context
     * @return the registry
     */
    static GeneratedPropertySources of(AOTContext context) {
        return context.get(GeneratedPropertySources.class).orElseGet(() -> {
            var created = new GeneratedPropertySources();
            context.put(GeneratedPropertySources.class, created);
            return created;
        });
    }

    void add(Source source) {
        sources.add(source);
    }

    List<Source> sources() {
        return Collections.unmodifiableList(sources);
    }

    /**
     * A generated property source.
     *
     * @param resource the resource it was read from, for example {@code application}
     * @param name the name of the property source, for example {@code application} or {@code application-dev}
     * @param simpleClassName the simple name of the generated class, in the generated package
     * @param files the configuration files that the generated class replaces
     */
    record Source(String resource, String name, String simpleClassName, List<String> files) {
    }
}
